### ISSUE TITLE
Opensource the App Script Code, If Possible 😅

### ISSUE THREAD

**Issue by Tibinsunny** [mbcbot/mbcbot.github.io#1]
Hey,
The Repo just contains the front-end template and stuffs. Looks like the App Script needs to be Open-Sourced for a better contribution form Open Source community. 

Cheers🍕🍕

**Comment by A5H1Q** [comment]
Uploaded the [Appscript](https://github.com/mbcbot/mbcbot.github.io/blob/main/App.gs#L1-L249)

I Appreciate the enthusiasm, Looking forward to more suggestions and commits.
Peace ✌
